# Generated by Django 5.1.7 on 2025-03-16 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_car_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
